//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitolaMVC.Database1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puhelintiedot
    {
        public int PuhelintietoID { get; set; }
        public string Puhelin_1 { get; set; }
        public string Puhelin_2 { get; set; }
        public string Puhelin_3 { get; set; }
    }
}
