//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitolaMVC.Database1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekisterointi
    {
        public int Kurssi_ID { get; set; }
        public string Kurssi { get; set; }
        public int Hoitaja_ID { get; set; }
    
        public virtual Hoitajat Hoitajat { get; set; }
        public virtual Kurssit Kurssit { get; set; }
    }
}
