//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointJalkahoitolaMVC.Database1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varauskalenteri
    {
        public int VarausID { get; set; }
        public Nullable<System.DateTime> Päivämäärä { get; set; }
        public Nullable<System.DateTime> Aika { get; set; }
        public Nullable<int> AsiakasID { get; set; }
        public string PalveluID { get; set; }
        public string Hoitopaikka { get; set; }
        public int HoitajaID { get; set; }
    }
}
