CREATE TABLE [dbo].[Hoitajat] (
    [Hoitaja_ID]        INT            IDENTITY (1, 1) NOT NULL,
    [Tunnus]            NVARCHAR (50)  NULL,
    [Etunimi]           NVARCHAR (50)  NULL,
    [Toinen nimi]       NVARCHAR (50)  NULL,
    [Sukunimi]          NVARCHAR (50)  NULL,
    [Katuosoite]        NVARCHAR (100) NULL,
    [Postinumero]       NVARCHAR (5)   NULL,
    [Postitoimipaikka]  NVARCHAR (100) NULL,
    [Henkilotunnus]     NVARCHAR (20)  NULL,
    [Aloituspvm]        DATE           NULL,
    [Valmistumispvm]    DATE           NULL,
    [Keskeytyspvm]      DATE           NULL,
    [Tiedot arkistoitu] VARCHAR (5)    NULL,
    [Huomio_ID]         INT            NULL,
    [Osoite_ID]         INT            NULL,
    [Puhelin_ID]        INT            NULL,
    [Kurssi_ID]         INT            NULL,
    [Rekisterointi_ID]  INT            NULL,
    [Palvelu_ID]        INT            NULL,
    [Asiakas_ID]        INT            NULL,
    [Varaus_ID]         INT            NULL,
    PRIMARY KEY CLUSTERED ([Hoitaja_ID] ASC),
    CONSTRAINT [FK_Hoitajat_ToTable_2] FOREIGN KEY ([Huomio_ID]) REFERENCES [dbo].[Huomiot] ([Huomio_ID]),
    CONSTRAINT [FK_Hoitajat_ToTable] FOREIGN KEY ([Osoite_ID]) REFERENCES [dbo].[Osoite] ([Osoite_ID]),
    CONSTRAINT [FK_Hoitajat_ToTable_1] FOREIGN KEY ([Puhelin_ID]) REFERENCES [dbo].[Puhelin] ([Puhelin_ID]),
    CONSTRAINT [FK_Hoitajat_ToTable_3] FOREIGN KEY ([Asiakas_ID]) REFERENCES [dbo].[Asiakkaat] ([Asiakas_ID]),
    CONSTRAINT [FK_Hoitajat_ToTable_4] FOREIGN KEY ([Varaus_ID]) REFERENCES [dbo].[Varaus] ([Varaus_ID]),
    CONSTRAINT [FK_Hoitajat_ToTable_5] FOREIGN KEY ([Palvelu_ID]) REFERENCES [dbo].[Palvelut] ([Palvelu_ID])
);

