//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JalkahoitolaWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaat
    {
        public int Asiakas_ID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Henkilotunnus { get; set; }
        public Nullable<int> Osoite_id { get; set; }
        public Nullable<int> Puhelin_id { get; set; }
        public Nullable<int> Huomio { get; set; }
    
        public virtual Osoite Osoite { get; set; }
        public virtual Puhelin Puhelin { get; set; }
        public virtual Huomiot Huomiot { get; set; }
    }
}
