//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JalkahoitolaWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jalkahoitola_dbEntities : DbContext
    {
        public Jalkahoitola_dbEntities()
            : base("name=Jalkahoitola_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakkaat> Asiakkaat { get; set; }
        public virtual DbSet<Huomiot> Huomiot { get; set; }
        public virtual DbSet<Osoite> Osoite { get; set; }
        public virtual DbSet<Puhelin> Puhelin { get; set; }
    }
}
