//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JohaMeriSQL2Entities : DbContext
    {
        public JohaMeriSQL2Entities()
            : base("name=JohaMeriSQL2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Huomiot> Huomiot { get; set; }
        public virtual DbSet<Postitoimipaikat> Postitoimipaikat { get; set; }
        public virtual DbSet<Varauskalenteri> Varauskalenteri { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Hoitopaikat> Hoitopaikat { get; set; }
        public virtual DbSet<Toimipisteet> Toimipisteet { get; set; }
        public virtual DbSet<Asiakkaat> Asiakkaat { get; set; }
        public virtual DbSet<Henkilokunta> Henkilokunta { get; set; }
        public virtual DbSet<Shippers> Shippers { get; set; }
        public virtual DbSet<Tilaukset> Tilaukset { get; set; }
        public virtual DbSet<Tuotteet> Tuotteet { get; set; }
        public virtual DbSet<Palvelut> Palvelut { get; set; }
        public virtual DbSet<Hoitajat> Hoitajat { get; set; }
        public virtual DbSet<Kurssi> Kurssi { get; set; }
        public virtual DbSet<Rekisterointi> Rekisterointi { get; set; }
        public virtual DbSet<Puhelin> Puhelin { get; set; }
        public virtual DbSet<Osoite> Osoite { get; set; }
        public virtual DbSet<Varaus> Varaus { get; set; }
    }
}
