//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arkistot
    {
        public int Arkisto_ID { get; set; }
        public string Tunnus { get; set; }
        public string Etunimi { get; set; }
        public string Toinen_nimi { get; set; }
        public string Sukunimi { get; set; }
        public string Katuosoite { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public string Henkilotunnus { get; set; }
        public Nullable<System.DateTime> Aloituspvm { get; set; }
        public Nullable<System.DateTime> Valmistumispvm { get; set; }
        public Nullable<System.DateTime> Keskeytyspvm { get; set; }
        public string Tiedot_arkistoitu { get; set; }
        public Nullable<int> Huomio_ID { get; set; }
        public Nullable<int> Osoite_ID { get; set; }
        public Nullable<int> Puhelin_ID { get; set; }
        public Nullable<int> Kurssi_ID { get; set; }
        public int Rekisterointi_ID { get; set; }
        public Nullable<int> Palvelu_ID { get; set; }
        public Nullable<int> Asiakas_ID { get; set; }
        public Nullable<int> Varaus_ID { get; set; }
        public string Sahkoposti { get; set; }
        public string Puhelinnumero_1 { get; set; }
        public int Hoitaja_ID { get; set; }
        public Nullable<System.DateTime> ArkistointiPvm { get; set; }
    
        public virtual Osoite Osoite { get; set; }
        public virtual Puhelin Puhelin { get; set; }
        public virtual Huomiot Huomiot { get; set; }
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual Varaus Varaus { get; set; }
        public virtual Palvelut Palvelut { get; set; }
        public virtual Hoitajat Hoitajat { get; set; }
    }
}
