//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakkaat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiakkaat()
        {
            this.Event = new HashSet<Event>();
            this.Hoitajat1 = new HashSet<Hoitajat>();
            this.Osoite1 = new HashSet<Osoite>();
            this.Palvelut1 = new HashSet<Palvelut>();
            this.Puhelin1 = new HashSet<Puhelin>();
            this.Varaus1 = new HashSet<Varaus>();
            this.Arkistot = new HashSet<Arkistot>();
        }
    
        public int Asiakas_ID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Katuosoite { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public string Henkilotunnus { get; set; }
        public string Puhelinnumero_1 { get; set; }
        public string Huomiot { get; set; }
        public Nullable<int> Osoite_id { get; set; }
        public Nullable<int> Huomio_id { get; set; }
        public Nullable<int> Puhelin_id { get; set; }
        public Nullable<int> Hoitaja_ID { get; set; }
        public Nullable<int> Varaus_ID { get; set; }
        public Nullable<int> Palvelu_ID { get; set; }
        public string Asiakastunnus { get; set; }
        public string Sahkoposti { get; set; }
    
        public virtual Osoite Osoite { get; set; }
        public virtual Puhelin Puhelin { get; set; }
        public virtual Huomiot Huomiot1 { get; set; }
        public virtual Hoitajat Hoitajat { get; set; }
        public virtual Varaus Varaus { get; set; }
        public virtual Palvelut Palvelut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitajat> Hoitajat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osoite> Osoite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palvelut> Palvelut1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puhelin> Puhelin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Varaus> Varaus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arkistot> Arkistot { get; set; }
    }
}
