//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Osoite()
        {
            this.Henkilokunta = new HashSet<Henkilokunta>();
            this.Hoitajat = new HashSet<Hoitajat>();
            this.Shippers1 = new HashSet<Shippers>();
            this.Toimipisteet1 = new HashSet<Toimipisteet>();
            this.Asiakkaat = new HashSet<Asiakkaat>();
            this.Arkistot = new HashSet<Arkistot>();
        }
    
        public int Osoite_ID { get; set; }
        public string Katuosoite { get; set; }
        public string Postinumero { get; set; }
        public string Postitoimipaikka { get; set; }
        public Nullable<int> Asiakas_ID { get; set; }
        public Nullable<int> Hoitaja_ID { get; set; }
        public Nullable<int> Henkilokunta_ID { get; set; }
        public Nullable<int> Toimipiste_ID { get; set; }
        public Nullable<int> Shipper_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Henkilokunta> Henkilokunta { get; set; }
        public virtual Henkilokunta Henkilokunta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitajat> Hoitajat { get; set; }
        public virtual Hoitajat Hoitajat1 { get; set; }
        public virtual Toimipisteet Toimipisteet { get; set; }
        public virtual Shippers Shippers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shippers> Shippers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toimipisteet> Toimipisteet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakkaat> Asiakkaat { get; set; }
        public virtual Asiakkaat Asiakkaat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arkistot> Arkistot { get; set; }
    }
}
