//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekisterointi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rekisterointi()
        {
            this.Kurssi1 = new HashSet<Kurssi>();
        }
    
        public int Rekisterointi_ID { get; set; }
        public string Vuosikurssi { get; set; }
        public Nullable<System.DateTime> Vuosikurssi_aloitus_pvm { get; set; }
        public Nullable<System.DateTime> Vuosikurssi_lopetus_pvm { get; set; }
        public Nullable<int> Kurssi_ID { get; set; }
        public Nullable<int> Hoitaja_ID { get; set; }
    
        public virtual Hoitajat Hoitajat { get; set; }
        public virtual Kurssi Kurssi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurssi> Kurssi1 { get; set; }
    }
}
