//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekisterointi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rekisterointi()
        {
            this.Kurssit = new HashSet<Kurssit>();
        }
    
        public int Rekisterointi_ID { get; set; }
        public Nullable<int> Kurssi_ID { get; set; }
        public string Kurssi { get; set; }
        public Nullable<int> Hoitaja_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurssit> Kurssit { get; set; }
        public virtual Kurssit Kurssit1 { get; set; }
        public virtual Hoitajat Hoitajat { get; set; }
    }
}
