//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shippers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shippers()
        {
            this.Puhelin = new HashSet<Puhelin>();
            this.Osoite = new HashSet<Osoite>();
        }
    
        public int Shipper_ID { get; set; }
        public string Yritysnimi { get; set; }
        public string Puhelinnumero_1 { get; set; }
        public string Huomiot { get; set; }
        public Nullable<int> Osoite_id { get; set; }
        public Nullable<int> Huomio_id { get; set; }
        public Nullable<int> Puhelin_id { get; set; }
    
        public virtual Huomiot Huomiot1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puhelin> Puhelin { get; set; }
        public virtual Puhelin Puhelin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osoite> Osoite { get; set; }
        public virtual Osoite Osoite1 { get; set; }
    }
}
