//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilaukset
    {
        public int Tilaus_ID { get; set; }
        public Nullable<int> Toimittaja_ID { get; set; }
        public Nullable<int> Tuote_ID { get; set; }
        public Nullable<int> Henkilokunta_ID { get; set; }
        public Nullable<int> Tilausmäärä { get; set; }
        public Nullable<System.DateTime> Tilauspäivä { get; set; }
        public Nullable<System.DateTime> Toimitus_pvm { get; set; }
        public Nullable<System.DateTime> Saapumispvm { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress { get; set; }
        public Nullable<int> Shipper_ID { get; set; }
    
        public virtual Tuotteet Tuotteet { get; set; }
    }
}
