//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuotteet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuotteet()
        {
            this.Tilaukset = new HashSet<Tilaukset>();
        }
    
        public int Tuote_ID { get; set; }
        public string Tuotenimi { get; set; }
        public Nullable<int> Toimittaja_ID { get; set; }
        public Nullable<decimal> Ostohinta { get; set; }
        public Nullable<System.DateTime> Tilauspäivä { get; set; }
        public Nullable<System.DateTime> Arvioitu_saapumis_pvm { get; set; }
        public Nullable<System.DateTime> Saapumispvm { get; set; }
        public Nullable<int> Tilaus_ID { get; set; }
        public Nullable<int> Shipper_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tilaukset> Tilaukset { get; set; }
    }
}
