//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointAjanvarausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varaus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Varaus()
        {
            this.Asiakkaat = new HashSet<Asiakkaat>();
            this.Hoitajat1 = new HashSet<Hoitajat>();
            this.Hoitopaikat1 = new HashSet<Hoitopaikat>();
            this.Palvelut1 = new HashSet<Palvelut>();
            this.Toimipisteet = new HashSet<Toimipisteet>();
            this.Arkistot = new HashSet<Arkistot>();
        }
    
        public int Varaus_ID { get; set; }
        public Nullable<int> Hoitaja_ID { get; set; }
        public Nullable<int> Hoitopaikka_ID { get; set; }
        public Nullable<int> Asiakas_ID { get; set; }
        public string Alku { get; set; }
        public string Loppu { get; set; }
        public string Palvelun_nimi { get; set; }
        public Nullable<int> Palvelu_ID { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> pvm { get; set; }
        public string Info { get; set; }
        public Nullable<int> Toimipiste_ID { get; set; }
    
        public virtual Hoitajat Hoitajat { get; set; }
        public virtual Hoitopaikat Hoitopaikat { get; set; }
        public virtual Palvelut Palvelut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakkaat> Asiakkaat { get; set; }
        public virtual Asiakkaat Asiakkaat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitajat> Hoitajat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoitopaikat> Hoitopaikat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palvelut> Palvelut1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toimipisteet> Toimipisteet { get; set; }
        public virtual Toimipisteet Toimipisteet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arkistot> Arkistot { get; set; }
    }
}
